### ISSUE TITLE
local variable 'hostname' referenced before assignment

### ISSUE THREAD

**Issue by dan-aksenov** [Lelik13a/Zabbix-PyOra-ActiveCheck#1]
Got
``UnboundLocalError: local variable 'hostname' referenced before assignment``
while running
``pyora-active.py  --address 10.0.0.1 --database SID``

``pyora-discovery.py --address db_address --database db_SID show_tablespaces``
works fine.

**Comment by dan-aksenov** [comment]
my mistake
misunderstood "hostname" naming in pyora-items-list.py
at first made
``--hostname "SID on db_host"``
Started working when chanded to match zabbix agent's hostname.

**Comment by dmjaya** [comment]
Hi 
do you know Zabbix-PyOra-ActiveCheck configuration for oracle db monitoring?
