### ISSUE TITLE
pyora-active.py failed

### ISSUE THREAD

**Issue by abilseiit** [Lelik13a/Zabbix-PyOra-ActiveCheck#11]
hello, i couldn't start pyora-active.py, i get next error message:
{"processed": 37, "failed": 0, "total": 37, "time": "0.000825", "chunk": 1}
{"processed": 1, "failed": 0, "total": 1, "time": "0.000052", "chunk": 1}
could you help to solve please?
Thank you.

UPD
i started scripts with -v key and i see all data send operation end with err, what is it mean?  
Data to send:
[{"host": "test", "key": "dbscattread", "value": "62303978"}]
{"processed": 1, "failed": 0, "total": 1, "time": "0.000030", "chunk": 1}

**Comment by Lelik13a** [comment]
But this is normal work.
 "failed": 0 - data send to zabbix.

May be need check host config in zabbix.

**Comment by abilseiit** [comment]
> May be need check host config in zabbix.
total": 37, - is it count of data? 
may be i had mistake when filling macro, do i need use brace? is it right "{$ADDRESS}" or "$ADDRESS" is right?

**Comment by Lelik13a** [comment]
> may be i had mistake when filling macro, do i need use brace? is it right "{$ADDRESS}" or "$ADDRESS" is right?

{$ADDRESS} - address oracle database.
Check host items and latest data.

Check directory content /usr/lib/zabbix/cache - items list for every database.

**Comment by abilseiit** [comment]
> Check directory content /usr/lib/zabbix/cache - items list for every database.

in /usr/lib/zabbix/cache i have items-192.168.10.10-testdb.list file with next entries: 
testdb,activeusercount
testdb,bufbusywaits
testdb,check_active
testdb,commits

is it normal?

**Comment by Lelik13a** [comment]
Yes.
This is items will be sent to zabbix host.
