### ISSUE TITLE
pyora-active.py output error

### ISSUE THREAD

**Issue by wang509020** [Lelik13a/Zabbix-PyOra-ActiveCheck#12]
hello, i couldn't start pyora-active.py, i get next error message:
# ./pyora-active.py  --address 10.171.7.56 --database yneda  -v
[Errno 2] No such file or directory: '/usr/lib/zabbix/cache/items-10.171.7.56-yneda.list'
# ll -d /usr/lib/zabbix/cache/
drwxr-xr-x 2 zabbix zabbix 6 Apr 23 10:08 /usr/lib/zabbix/cache/
# ll  /usr/lib/zabbix/cache/
total 0
why? pyora-active.py don't create file or directory to /usr/lib/zabbix/cache ，pls help me
@Lelik13a @batdelger @dan-aksenov

**Comment by wang509020** [comment]
i don't know this error ,pls help me

**Comment by Lelik13a** [comment]
Hello.
First need pyora-items-list.py  and pyora-discovery.py  - wait when zabbix run it for host or run it manually.

**Comment by wang509020** [comment]
@Lelik13a ,ok,I do it ,and the zabbix is monitoring the oracle database
but I monitoring oracle ,and find "oracle raw" items is "unsupported item key"
![image](https://user-images.githubusercontent.com/50124188/116015709-d11dc500-a66c-11eb-87ab-33b231354260.png)

**Comment by wang509020** [comment]
@Lelik13a ,pls tell me ,this question is why? I waiting ,thks.

**Comment by wang509020** [comment]
@Lelik13a 
# ./pyora-items-list.py  --zabbixurl http://x.x.x.x --zabbixuser "********" --zabbixpassword "**********" --hostname "*****" --address "x.x.x.x" --database "********"
OK
./pyora-discovery.py  --address x.x.x.x --database *******  show_tablespaces
{"data": [{"{#TABLESPACE}": "GOLDENGATE"}, {"{#TABLESPACE}": "KANBAN"}, {"{#TABLESPACE}": "SMTBS"}, {"{#TABLESPACE}": "SMTBSIDX"}, {"{#TABLESPACE}": "SMTRT"}, {"{#TABLESPACE}": "SMTRTIDX"}, {"{#TABLESPACE}": "SYSAUX"}, {"{#TABLESPACE}": "SYSBS"}"{#TABLESPACE}": "UNDOTBS2"}, {"{#TABLESPACE}": "USERS"}]}
# ./pyora-active.py  --address x.x.x.x --database *******  -v
Processing: uptime
                        9736748
Data to send:
[{"host": "yneda", "key": "uptime", "value": "9736748"}]
{"processed": 1, "failed": 0, "total": 1, "time": "0.000080", "chunk": 1}


Processing: version
                        Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
Data to send:
[{"host": "yneda", "key": "version", "value": "Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production"}]
{"processed": 1, "failed": 0, "total": 1, "time": "0.000085", "chunk": 1}



the python scripts  is do the oracle number,but oracle raw  show "unsupported item key",why?
and  the "oracle raw" items is unsupported item key?
 oracle_pyora.conf in /etc/zabbix/zabbix_agentd.d/
pyora-*.py   in /etc/zabbix/externalscripts/
the owner and user for zabbix in /usr/lib/zabbix/cache 
pls tell me why "oracle raw" items "unsupported item key",help me ,tks.
![image](https://user-images.githubusercontent.com/50124188/116019843-b6048280-a677-11eb-9f61-5de5536e5051.png)
![image](https://user-images.githubusercontent.com/50124188/116019883-cb79ac80-a677-11eb-9590-0305f4315b0b.png)
![image](https://user-images.githubusercontent.com/50124188/116019909-d7656e80-a677-11eb-89a6-c33466dee70f.png)
![image](https://user-images.githubusercontent.com/50124188/116019938-e4825d80-a677-11eb-85ba-7863955570d9.png)

**Comment by Lelik13a** [comment]
Zabbix agent config must be with `UserParameter=pyora-discovery`, see config  Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf

**Comment by wang509020** [comment]
hi,Lelik13a
oracle_pyora.conf
UserParameter=pyora-discovery[\*],/etc/zabbix/externalscripts/pyora-discovery.py --address $1 --database $2 --port $3 $4
UserParameter=pyora-items-list[\*],/etc/zabbix/externalscripts/pyora-items-list.py --zabbixurl "$1" --zabbixuser "$2" --zabbixpassword "$3" --hostname "$4" --address "$5" --database "$6"
and python scripts path ,I mv path: /etc/zabbix/externalscripts/ ,the path is zabbix_proxy.conf setting it.

**Comment by Lelik13a** [comment]
Restart agent.
Check config for include zabbix_agentd.d/*
`unsupported item key` - zabbix agent don't known requested item.

**Comment by wang509020** [comment]
@Lelik13a ,yes,i see
and I do it ,but don't find,the web is show "unsupported items key"
![image](https://user-images.githubusercontent.com/50124188/116036452-5028f280-a699-11eb-9989-5f91691b2d94.png)
![image](https://user-images.githubusercontent.com/50124188/116036484-5d45e180-a699-11eb-9768-5134926611a2.png)
![image](https://user-images.githubusercontent.com/50124188/116036498-63d45900-a699-11eb-82da-43827213ea86.png)
![image](https://user-images.githubusercontent.com/50124188/116036591-836b8180-a699-11eb-83a6-e615b9286b3a.png)

**Comment by Lelik13a** [comment]
You mast use `include` with path to  Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf

**Comment by wang509020** [comment]
@Lelik13a ,
yes ,I do the number 7: Copy zabbix_agentd.d/oracle_pyora.conf to /etc/zabbix/zabbix_agentd.d/ and restart zabbix agent.
your "Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf" address is not /etc/zabbix/zabbix_agentd.d/ ?
and other path?

**Comment by wang509020** [comment]
> You mast use `include` with path to Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf

yes ,i copy oracle_pyora.conf  to /etc/zabbix/zabbix_agentd.d/,and systemctl restart zabbix-agent
I zabbix version :5.2.4
and the Zabbix-PyOra-ActiveCheck scripts in the zabbix-proxy ,the proxy's version is 5.2.4 ,you see it ,this is ok?

**Comment by Lelik13a** [comment]
I not tested with zabbix proxy.
But in zabbix proxy (or agent) config mast be `include` option with path to included config.
Or insert `UserParameter=...`  option directly in zabbix proxy (or agent) config.

**Comment by wang509020** [comment]
> I not tested with zabbix proxy.
> But in zabbix proxy (or agent) config mast be `include` option with path to included config.
> Or insert `UserParameter=...` option directly in zabbix proxy (or agent) config.
yes ,i set the pyora template's macros:

![image](https://user-images.githubusercontent.com/50124188/116041085-6043d080-a69f-11eb-96a4-fbd76c350f10.png)
the  macros {$ADDRESS} and {$DATABASE}  is for the specific host 

![image](https://user-images.githubusercontent.com/50124188/116041239-92553280-a69f-11eb-827b-45b474cb6c47.png)

**Comment by wang509020** [comment]
@Lelik13a 
and sure ,the pyora script's is zabbix client's  or zabbix server's or zabbix proxy's,pls tell me ,tks.

**Comment by Lelik13a** [comment]
pyora scripts mast be run by zabbix agent - disovery and item list.
cron job  - pyora-active.py,  check and send results to zabbix server (or proxy).

**Comment by wang509020** [comment]
@Lelik13a 
I'm sorry, I manage the python monitor oracle in today,but I don't monitor oracle  in zabbix.
and I try the scripts to oracle in zabbix proxy or zabbix server,but i failure,try my best,I waive it ,sorry.

**Comment by wang509020** [comment]
thank you for your help
