### ISSUE TITLE
Database showing down

### ISSUE THREAD

**Issue by dmjaya** [Lelik13a/Zabbix-PyOra-ActiveCheck#13]
@Lelik13a 
I have installed Zabbix 5.4 and try to monitor oracle 12c DB but I didn't get any I'm not able to get the (# Perform checks by items list and print additional verbose information for every check).  can I know what is the issue It showing the database down?

Thanks in advance.

**Comment by Lelik13a** [comment]
I use this checks with zabbix 5.2 - all ok.
Test scripts and check rights.

**Comment by dmjaya** [comment]
Noted Could you please check my screen outputs below

![image](https://user-images.githubusercontent.com/13479490/122266944-f950d400-cef7-11eb-96a0-20cb07c8d158.png)

![image](https://user-images.githubusercontent.com/13479490/122266996-08d01d00-cef8-11eb-804f-9e069ea3da65.png)

![image](https://user-images.githubusercontent.com/13479490/122267074-1ab1c000-cef8-11eb-8fce-60979bff9b7f.png)

@Lelik13a

**Comment by Lelik13a** [comment]
First two seems OK.
Check directory content `/usr/lib/zabbix/cache` there should be a list of items to check.

**Comment by dmjaya** [comment]
Thanks for responding @Lelik13a  yes there is a file but empty for your reference I attached some screenshots.

![image](https://user-images.githubusercontent.com/13479490/122323017-0b586400-cf44-11eb-9fae-074a5094b27e.png)

![image](https://user-images.githubusercontent.com/13479490/122323068-2034f780-cf44-11eb-96b7-6d4f0a6086fa.png)

![image](https://user-images.githubusercontent.com/13479490/122323115-35aa2180-cf44-11eb-9689-cea58275f630.png)

![image](https://user-images.githubusercontent.com/13479490/122323286-7c981700-cf44-11eb-8852-4a3f24fe5a51.png)

![image](https://user-images.githubusercontent.com/13479490/122323882-72c2e380-cf45-11eb-9175-05fc3ed2d190.png)

in the last image, some values ($) are not tallying with the **MACRO** order.

Please help me @Lelik13a 

Thanks in advance

**Comment by Lelik13a** [comment]
check content file items-...  and its rights.
You run scripts by root - may be zabbix cant access to items list.
Check run scripts with zabbix rights.

**Comment by dmjaya** [comment]
check content file items-... and its rights. what do you mean? which files I'll attach files in below

![image](https://user-images.githubusercontent.com/13479490/122419266-69b72e00-cfa8-11eb-9348-953b49fee1cd.png)

You run scripts by root - may be zabbix cant access the items list. (Yes I think this is the issue) how I can give access to the Zabbix user? Please help me I'm in big trouble 
@Lelik13a

**Comment by Lelik13a** [comment]
Check content files in directory `/usr/lib/zabbix/cache`
Change owner and rights:
```
chown -R zabbix /usr/lib/zabbix/cache
chmod -R u+rwX,a+rX /usr/lib/zabbix/cache
```

**Comment by dmjaya** [comment]
Hi,
Thanks for the support @Lelik13a I'm facing the issue. Thanks for your support and the comments.

Thanks in advance
