### ISSUE TITLE
oracle_pyora.conf is not updated

### ISSUE THREAD

**Issue by batdelger** [Lelik13a/Zabbix-PyOra-ActiveCheck#9]
I think you forgot to update **oracle_pyora.conf** file with ORAPORT related changes.

`UserParameter=pyora-discovery[*],/usr/lib/zabbix/externalscripts/pyora-discovery.py --address $1 --database $2 $3
` -->
`UserParameter=pyora-discovery[*],/usr/lib/zabbix/externalscripts/pyora-discovery.py --address $1 --database $2 --port $3 $4`

**Comment by Lelik13a** [comment]
Fixed, thanks :).
